import { Geist, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation-components/navbar";
import Footer from "./components/navigation-components/footer";
import Header from "./components/navigation-components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${roboto.variable} antialiased`}>
      <Header/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
